-- 创建 app 数据库
CREATE DATABASE IF NOT EXISTS `app` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `app`;

-- 订单表
CREATE TABLE IF NOT EXISTS `orders` (
  `id` VARCHAR(64) NOT NULL COMMENT '订单ID',
  `user_id` VARCHAR(64) NOT NULL COMMENT '用户ID',
  `product` VARCHAR(255) NOT NULL COMMENT '产品名称',
  `quantity` INT NOT NULL DEFAULT 1 COMMENT '数量',
  `price` DECIMAL(10,2) NOT NULL COMMENT '价格',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '订单状态: pending, shipped, completed',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表';

-- 用户表
CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(64) NOT NULL COMMENT '用户ID',
  `name` VARCHAR(128) NOT NULL COMMENT '用户姓名',
  `email` VARCHAR(255) NOT NULL COMMENT '用户邮箱',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_email` (`email`),
  INDEX `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 员工表
CREATE TABLE IF NOT EXISTS `employees` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `name` VARCHAR(128) NOT NULL COMMENT '员工姓名',
  `position` VARCHAR(128) NOT NULL COMMENT '工作岗位',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  INDEX `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工表';

-- 插入订单测试数据
INSERT INTO `orders` (`id`, `user_id`, `product`, `quantity`, `price`, `status`, `create_time`) VALUES
('ORDER-001', 'user-1', 'iPhone 15 Pro', 1, 7999.00, 'completed', '2024-01-15 10:30:00'),
('ORDER-002', 'user-2', 'MacBook Pro 14', 1, 14999.00, 'shipped', '2024-01-16 14:20:00'),
('ORDER-003', 'user-1', 'AirPods Pro', 2, 1899.00, 'pending', '2024-01-17 09:15:00');

-- 插入用户测试数据
INSERT INTO `users` (`id`, `name`, `email`) VALUES
('user-1', '张三', 'zhangsan@example.com'),
('user-2', '李四', 'lisi@example.com'),
('user-3', '王五', 'wangwu@example.com');

-- 插入员工测试数据（115 条）
INSERT INTO `employees` (`name`, `position`) VALUES
('张伟', '后端开发'),
('王芳', '前端开发'),
('李娜', '产品经理'),
('刘洋', '项目经理'),
('陈静', 'UI 设计'),
('杨帆', '后端开发'),
('陈龙', '前端开发'),
('孙杰', '产品组长'),
('周婷', '后端开发'),
('吴强', '前端开发'),
('徐丽', '产品经理'),
('朱磊', '项目经理'),
('胡琳', 'UI 设计'),
('郭军', '后端开发'),
('林涛', '前端开发'),
('何梅', '产品组长'),
('高远', '后端开发'),
('罗丹', '前端开发'),
('梁伟', '产品经理'),
('宋佳', '项目经理'),
('谢峰', 'UI 设计'),
('唐雪', '后端开发'),
('许亮', '前端开发'),
('邓丽', '产品组长'),
('冯杰', '后端开发'),
('曹敏', '前端开发'),
('彭涛', '产品经理'),
('曾强', '项目经理'),
('萧雅', 'UI 设计'),
('董磊', '后端开发'),
('袁丽', '前端开发'),
('潘峰', '产品组长'),
('于涛', '后端开发'),
('蒋梅', '前端开发'),
('蔡伟', '产品经理'),
('徐佳', '项目经理'),
('叶琳', 'UI 设计'),
('阎杰', '后端开发'),
('苏丽', '前端开发'),
('魏强', '产品组长'),
('程涛', '后端开发'),
('吕敏', '前端开发'),
('丁磊', '产品经理'),
('任丽', '项目经理'),
('沈峰', 'UI 设计'),
('姚伟', '后端开发'),
('卢佳', '前端开发'),
('姜涛', '产品组长'),
('崔杰', '后端开发'),
('钟丽', '前端开发'),
('汪强', '产品经理'),
('田敏', '项目经理'),
('范磊', 'UI 设计'),
('金伟', '后端开发'),
('熊佳', '前端开发'),
('秦涛', '产品组长'),
('邱杰', '后端开发'),
('侯丽', '前端开发'),
('龙强', '产品经理'),
('尹敏', '项目经理'),
('黎磊', 'UI 设计'),
('易伟', '后端开发'),
('常佳', '前端开发'),
('武涛', '产品组长'),
('乔杰', '后端开发'),
('贺丽', '前端开发'),
('赖强', '产品经理'),
('龚敏', '项目经理'),
('文磊', 'UI 设计'),
('伍伟', '后端开发'),
('余强', '前端开发'),
('元涛', '产品组长'),
('卜杰', '后端开发'),
('顾丽', '前端开发'),
('孟强', '产品经理'),
('平敏', '项目经理'),
('黄磊', 'UI 设计'),
('和伟', '后端开发'),
('穆佳', '前端开发'),
('萧涛', '产品组长'),
('尹杰', '后端开发'),
('姚丽', '前端开发'),
('邵强', '产品经理'),
('湛敏', '项目经理'),
('汪磊', 'UI 设计'),
('祁伟', '后端开发'),
('毛佳', '前端开发'),
('常涛', '产品组长'),
('康杰', '后端开发'),
('严丽', '前端开发'),
('钱强', '产品经理'),
('华敏', '项目经理'),
('金磊', 'UI 设计'),
('陶伟', '后端开发'),
('姜佳', '前端开发'),
('谢涛', '产品组长'),
('邹杰', '后端开发'),
('喻丽', '前端开发'),
('柏强', '产品经理'),
('水敏', '项目经理'),
('窦磊', 'UI 设计'),
('章伟', '后端开发'),
('云佳', '前端开发'),
('苏涛', '产品组长'),
('潘杰', '后端开发'),
('葛丽', '前端开发'),
('俞强', '产品经理'),
('方敏', '项目经理'),
('任磊', 'UI 设计'),
('张三', '后端开发'),
('李四', '前端开发'),
('王五', '产品经理'),
('赵六', '项目经理'),
('孙七', 'UI 设计');
